/**
 * @description DummyClass
 */
    public with sharing class Dummy {
    /**
     * @description Contructor
     */
    public Integer instanceProperty { get; set; } // bad

    /**
     * @description Contructor
     */

    public Dummy() {
        
    }
    
    /**
     * @description dummy Method
     */   
     private void myDummyMethod() {

        String LocalVariable;
        system.debug('testing a scan 2');

    }
}